<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Silverpop\Factory\Service\Silverpop'         => __DIR__ . '/src/Silverpop/Factory/Service/Silverpop.php',
    'Silverpop\Factory\Transfer\Transfer'         => __DIR__ . '/src/Silverpop/Factory/Transfer/Transfer.php',
    'Silverpop\Factory\Transfer\Adapter\Sftp'     => __DIR__ . '/src/Silverpop/Factory/Transfer/Adapter/Sftp.php',
    'Silverpop\Service\Silverpop'                 => __DIR__ . '/src/Silverpop/Service/Silverpop.php',
    'Silverpop\Transfer\Adapter\AbstractAdapter'  => __DIR__ . '/src/Silverpop/Transfer/Adapter/AbstractAdapter.php',
    'Silverpop\Transfer\Adapter\Sftp'             => __DIR__ . '/src/Silverpop/Transfer/Adapter/Sftp.php',
    'Silverpop\Transfer\Adapter\AdapterInterface' => __DIR__ . '/src/Silverpop/Transfer/Adapter/AdapterInterface.php',
    'Silverpop\Module'                            => __DIR__ . '/Module.php',
);